name: TestRail CLI
on: [push, workflow_dispatch]
env:
  WORKING_DIRECTORY: sourcecode/QA/ui-automation/webuitest//pom.xml
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test -Dtest="OTSApiTest" --file "${{env.WORKING_DIRECTORY}}"
    - name: TestRail CLI upload results
      if: always()
      run: |
       pip install trcli
       trcli  `
         -h " https://saiaravind123.testrail.io/" `
         -u "aravindsai879@gmail.com" `
         -p "9Nb3rW2TxykjsXlNGkBF" `
         --project "Sample Project" `
         parse_junit `
         --title "Automated Tests Run" `
         -f "test-output/junitreports/TEST-com.runway.test.api.OTSApiTest.xml"
        
      
